services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fe0c836613916e4f97be69054a56798f
    ports:
      - "5432:5432"
