openapi: "3.0.0"
info:
  title: "RED Modding Tools Backend Api"
  description: "This is the RED Modding Tools Backend Api documentation"
  version: "0.2.0"

servers:
  - url: "http://localhost:3000/api"
    description: "Local server"

paths:
  /bot/commands/core-versions:
    get:
      summary: Github Core Plugin Versions
      tags:
        - Bot
        
  /bot/commands/core-versions/update:
    get:
      summary: Manuel Updater for Core Plugin Versions
      tags:
        - Bot
  /bot/commands/quotes:
    get:
      summary: Bot.
      description: Quotes
      tags:
        - Bot
  /bot/commands/respond:
    get:
      summary: Bot.
      description: Responses
      tags:
        - Bot
  /bot/commands/trivia:
    get:
      summary: Bot.
      description: Trivia
      tags:
        - Bot
  /bot/commands/user:
    get:
      summary: Bot.
      description: Quotes
      tags:
        - Bot
  /bot/dev/user:
    get:
      summary: Bot.
      description: Quotes
      tags:
        - Bot
  /bot/team/pass:
    get:
      summary: Bot.
      description: Quotes
      tags:
        - Bot

  /discord:
    get:
      summary: Discord.
      description: Get the Discord invite link.
      tags:
        - Discord

  /endpoint:
    get:
      summary: Endpoint.
      description: Get the endpoint.
      tags:
        - Endpoint

  /metrics:
    get:
      summary: Prometheus Metrics.
      description: Get the Prometheus metrics.
      tags:
        - Metrics
